---
- name: Ping Test
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ping Test
      ansible.builtin.ping:
    - name: Hello World Message From Inventory Hosts
      ansible.builtin.debug:
        msg: "Hello World From {{ inventory_hostname }}!!!"
